version: "3"

services:
  database:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  api:
    build: ./server
    env_file:
      - .env
    environment:
      DATABASE_URL: $DATABASE_URL
      PORT_API: $PORT_API
    ports:
      - "8000:8000"
    depends_on:
      - database
  client:
    build: ./client
    env_file:
      - .env
    environment:
      POSTGRES_URL: $POSTGRES_URL 
      POSTGRES_PRISMA_URL: $POSTGRES_PRISMA_URL
      POSTGRES_URL_NON_POOLING: $POSTGRES_URL_NON_POOLING
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      PORT_WEB: $PORT_WEB
      AUTH_SECRET=: $AUTH_SECRET
      AUTH_URL: $AUTH_URL
    ports:
      - "3000:3000"
    depends_on:
      - api
      - database